### ISSUE TITLE
1.0 TODO list.

### ISSUE THREAD

**Issue by Matriks404** [Matriks404/i4040emu#2]
#Emulation features
- [x] Registers from ir0 and ir1 banks (16 and 8 registers each)
- [x] Accumulator
- [x] Program counter
- [ ] Test bit (it's there but not used)
- [ ] ROM support.
- [ ] ROM banks (support for changing them via instructions is there)
- [x] RAM pointer
- [ ] Interrupts
- [ ] Clock speed
- [ ] All instructions
  - [x] NOP
  - [ ] HLT
  - [ ] BBS
  - [ ] LCR
  - [x] OR4
  - [x] OR5
  - [x] AN6
  - [x] AN7
  - [x] DB0
  - [x] DB1
  - [x] IR0
  - [x] IR1
  - [ ] EIN
  - [ ] DIN
  - [ ] RPM
  - [x] 0x0F NOP?
  - [ ] JCN
  - [x] FIM
  - [x] SRC
  - [ ] FIN
  - [x] JIN
  - [ ] JUN (not working properly right now)
  - [ ] INC
  - [ ] ISZ
  - [ ] ADD
  - [ ] SUB
  - [ ] LD
  - [ ] XCH
  - [ ] BBL
  - [ ] LDM
  - [ ] WRM
  - [ ] WMP
  - [ ] WRR
  - [ ] WPM
  - [ ] WR0
  - [ ] WR1
  - [ ] WR2
  - [ ] WR3
  - [ ] SBM
  - [ ] RDM
  - [ ] RDR
  - [ ] ADM
  - [ ] RD0
  - [ ] RD1
  - [ ] RD2
  - [ ] RD3
  - [ ] CLB
  - [ ] CLC
  - [ ] IAC
  - [ ] CMC
  - [ ] CMA
  - [ ] RAL
  - [ ] RAR
  - [ ] TCC
  - [ ] DAC
  - [ ] TCS
  - [ ] STC
  - [ ] DAA
  - [ ] KBP
  - [ ] DCL
  - [ ] 0xFE-0xFF NOPs?

#Interface
- [x] Very basic debugging info
- [ ] Useful debugger
- [ ] Specifying ROM, RAM size
- [ ] Specifying other stuff?
- [ ] Basic GUI with windows
